"""Application constants for Bulk Certificate Generator."""

# Public ID generation
ID_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"  # 32 characters, no 0, O, 1, I
ID_RANDOM_LENGTH = 8
JOB_ID_PREFIX = "JOB"
CERT_ID_PREFIX = "CERT"
JOB_ID_REGEX = r"^JOB-\d{4}-[A-HJ-NP-Z2-9]{8}$"
CERT_ID_REGEX = r"^CERT-\d{4}-[A-HJ-NP-Z2-9]{8}$"

# Length limits (from PRD Section 9)
MIN_EVENT_NAME_LENGTH = 3
MAX_EVENT_NAME_LENGTH = 100

MIN_ORGANIZATION_NAME_LENGTH = 2
MAX_ORGANIZATION_NAME_LENGTH = 80

MIN_SIGNATORY_LENGTH = 2
MAX_SIGNATORY_LENGTH = 50

MIN_RECIPIENT_NAME_LENGTH = 2
MAX_RECIPIENT_NAME_LENGTH = 60

MAX_EMAIL_LENGTH = 254
